export class DeliveryRequest {
    deliveryRequestId;
    deliveryRequestCode;
    type;
    typeDisplay;
    contactName;
    contactPhone;
    address;
    country;
    countryDisplay;
    city;
    cityDisplay;
    district;
    districtDisplay;
    ward;
    wardDisplay;
    description;
    vehicleName;
    vehiclePhone;
    vehicleAddress;
    userId;
    createdDate;
    createdUser;
    changeDate;
    changeUserId;
    warehouseId;
    warehouseName;
    status;
    statusDisplay;
    missingAmount;
    warehouseExp;
    shipment: any[];
    lsParentDetail: any[];
    lsDetail: any[];
}
